#!/bin/sh

set -eu

script_directory=$(CDPATH= cd "$(dirname "$0")" && pwd)
repository_path=${CI_PRIMARY_REPOSITORY_PATH:-$(CDPATH= cd "$script_directory/../.." && pwd)}
output_path="$repository_path/client/MiaoJiConfig.xcconfig"

strip_surrounding_quotes() {
    value=$1
    case "$value" in
        \"*\") value=${value#\"}; value=${value%\"} ;;
        \'*\') value=${value#\'}; value=${value%\'} ;;
        “*”) value=${value#“}; value=${value%”} ;;
        ‘*’) value=${value#‘}; value=${value%’} ;;
    esac
    printf '%s' "$value"
}

api_base_url=$(strip_surrounding_quotes "${MIAOJI_API_BASE_URL:-}")
supabase_url=$(strip_surrounding_quotes "${SUPABASE_URL:-}")

if [ -z "$api_base_url" ]; then
    echo "error: MIAOJI_API_BASE_URL is not configured for this Xcode Cloud workflow." >&2
    exit 1
fi

if [ -z "$supabase_url" ]; then
    echo "error: SUPABASE_URL is not configured for this Xcode Cloud workflow." >&2
    exit 1
fi

# Keep generated xcconfig values predictable: URLs must be HTTPS and values
# may not contain characters that xcconfig would treat as comments or syntax.
if ! printf '%s' "$api_base_url" | grep -Eq '^https://[A-Za-z0-9.-]+(:[0-9]+)?(/[A-Za-z0-9._~!$&()*+,;=:@%/-]*)?$'; then
    echo "error: MIAOJI_API_BASE_URL must be a valid HTTPS URL without quotes, whitespace, query, or fragment." >&2
    exit 1
fi

if ! printf '%s' "$supabase_url" | grep -Eq '^https://[A-Za-z0-9.-]+\.supabase\.co/?$'; then
    echo "error: SUPABASE_URL must be an HTTPS *.supabase.co URL." >&2
    exit 1
fi

# xcconfig interprets // as a comment, so use Apple's $()/ idiom to emit the
# second slash at build time.
api_base_url_xcconfig="https:/\$()/${api_base_url#https://}"
supabase_url_xcconfig="https:/\$()/${supabase_url#https://}"

cat > "$output_path" <<EOF
// Generated by client/ci_scripts/ci_post_clone.sh. Do not edit directly.
MIAOJI_API_BASE_URL = $api_base_url_xcconfig
SUPABASE_URL = $supabase_url_xcconfig
EOF

echo "Generated client/MiaoJiConfig.xcconfig for Xcode Cloud."
